version: 2
jobs:
  build:
    docker:
      - image: circleci/java:8
  steps:
    - checkout
    - run:
      name: Run JUnits
      command: |
        mvn test
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit