version: 2
jobs:
  build:
    docker:
      - image: circleci/java:8
  steps:
    - checkout
    - run:
      name: Run JUnits
      command: |
        mvn test
    - run:
      name: Save test results
      command: |
        mkdir -p ~/junit/
        find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
      when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit